# Generated by Django 4.2 on 2023-04-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=18)),
                ('income', models.IntegerField(default=20000)),
                ('employment_length', models.FloatField(default=3)),
                ('loan_amount', models.IntegerField(default=50000)),
                ('loan_intent', models.TextField(default='education')),
                ('loan_grade', models.CharField(default='B', max_length=1)),
                ('loan_intrest', models.FloatField(default=12)),
                ('loan_status', models.IntegerField(default=0)),
                ('loan_percent_income', models.FloatField(default=20000)),
                ('cb_person_default_on_file', models.CharField(default='N', max_length=1)),
                ('cb_credit_history_len', models.IntegerField(default=5)),
            ],
        ),
    ]
