# Generated by Django 4.2 on 2023-05-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banking',
            name='loan_percent_income',
            field=models.FloatField(default=20.1),
        ),
    ]
